<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AdditionalCustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // user_id = 3のユーザーを作成または取得
        $user = User::find(3);
        if (!$user) {
            $user = User::factory()->create([
                'name' => '営業次郎',
                'email' => 'sales2@example.com',
            ]);
            $this->command->info('ユーザーID 3を作成しました。');
        }

        // user_id = 3用の30件の顧客データ
        $customers = [
            [
                'user_id' => 3,
                'company_name' => '株式会社フューチャーテック',
                'contact_name' => '斎藤一郎',
                'email' => 'saito@future-tech.co.jp',
                'phone' => '03-5678-1234',
                'industry' => 'IT',
                'temperature_rating' => 'A',
                'area' => '関東',
                'status' => '見込みあり',
                'priority' => 5,
                'memo' => 'AI開発に強い興味。予算も確保済み。早急なアプローチが必要。',
            ],
            [
                'user_id' => 3,
                'company_name' => '東海製作所',
                'contact_name' => '加藤美香',
                'email' => 'kato@tokai-seisakusho.jp',
                'phone' => '052-7890-4567',
                'industry' => '製造業',
                'temperature_rating' => 'B',
                'area' => '中部',
                'status' => '会話のみ',
                'priority' => 3,
                'memo' => 'IoT導入を検討中。来期の予算で検討したいとのこと。',
            ],
            [
                'user_id' => 3,
                'company_name' => '九州商事株式会社',
                'contact_name' => '松本健太',
                'email' => 'matsumoto@kyushu-shoji.com',
                'phone' => '092-3456-7890',
                'industry' => '小売業',
                'temperature_rating' => 'C',
                'area' => '九州',
                'status' => '受けブロ',
                'priority' => 2,
                'memo' => '現在のシステムで満足している様子。',
            ],
            [
                'user_id' => 3,
                'company_name' => '北陸エネルギー',
                'contact_name' => '西村真理',
                'email' => 'nishimura@hokuriku-energy.jp',
                'phone' => '076-2345-6789',
                'industry' => 'その他',
                'temperature_rating' => 'A',
                'area' => '中部',
                'status' => '取引中',
                'priority' => 5,
                'memo' => '既存契約あり。追加サービスの提案中。',
            ],
            [
                'user_id' => 3,
                'company_name' => '関東メディカル',
                'contact_name' => '橋本裕子',
                'email' => 'hashimoto@kanto-medical.co.jp',
                'phone' => '048-9876-5432',
                'industry' => '医療・福祉',
                'temperature_rating' => 'B',
                'area' => '関東',
                'status' => '見込みあり',
                'priority' => 4,
                'memo' => '電子カルテシステムの更新を検討中。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社ニューホライズン',
                'contact_name' => '村田太一',
                'email' => 'murata@new-horizon.jp',
                'phone' => '06-5432-1098',
                'industry' => 'IT',
                'temperature_rating' => 'D',
                'area' => '関西',
                'status' => '競合サービス利用中',
                'priority' => 2,
                'memo' => '競合他社のサービスを利用中。切り替えは難しそう。',
            ],
            [
                'user_id' => 3,
                'company_name' => '東北建設工業',
                'contact_name' => '佐々木誠',
                'email' => 'sasaki@tohoku-kensetsu.com',
                'phone' => '022-8765-4321',
                'industry' => '建設・不動産',
                'temperature_rating' => 'C',
                'area' => '東北',
                'status' => '会話のみ',
                'priority' => 3,
                'memo' => 'プロジェクト管理ツールに興味あり。',
            ],
            [
                'user_id' => 3,
                'company_name' => 'グローバルフーズ',
                'contact_name' => '池田恵美',
                'email' => 'ikeda@global-foods.co.jp',
                'phone' => '03-2109-8765',
                'industry' => '飲食・宿泊',
                'temperature_rating' => 'B',
                'area' => '関東',
                'status' => '過去取引あり',
                'priority' => 3,
                'memo' => '以前取引あり。再度アプローチの価値あり。',
            ],
            [
                'user_id' => 3,
                'company_name' => '四国運送株式会社',
                'contact_name' => '吉田浩二',
                'email' => 'yoshida@shikoku-unso.jp',
                'phone' => '087-5678-9012',
                'industry' => '運輸・物流',
                'temperature_rating' => 'E',
                'area' => '四国',
                'status' => '受けブロ',
                'priority' => 1,
                'memo' => '配送管理システムの改善を検討中だが予算なし。',
            ],
            [
                'user_id' => 3,
                'company_name' => '中国地方銀行',
                'contact_name' => '藤田智子',
                'email' => 'fujita@chugoku-bank.jp',
                'phone' => '082-3456-7890',
                'industry' => '金融業',
                'temperature_rating' => 'A',
                'area' => '中国',
                'status' => '見込みあり',
                'priority' => 5,
                'memo' => 'フィンテック関連のソリューションに強い関心。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社スマートエデュケーション',
                'contact_name' => '岡本直樹',
                'email' => 'okamoto@smart-edu.jp',
                'phone' => '092-1234-5678',
                'industry' => '教育',
                'temperature_rating' => 'B',
                'area' => '九州',
                'status' => '会話のみ',
                'priority' => 4,
                'memo' => 'オンライン学習プラットフォームの導入を検討。',
            ],
            [
                'user_id' => 3,
                'company_name' => 'アドバンスコンサル',
                'contact_name' => '中島弁護士',
                'email' => 'nakajima@advance-consul.jp',
                'phone' => '06-9876-5432',
                'industry' => '士業・コンサル',
                'temperature_rating' => 'C',
                'area' => '関西',
                'status' => '競合サービス利用中',
                'priority' => 2,
                'memo' => '大手競合のサービスを利用中。',
            ],
            [
                'user_id' => 3,
                'company_name' => '北海道フレッシュ',
                'contact_name' => '川村和也',
                'email' => 'kawamura@hokkaido-fresh.com',
                'phone' => '011-5432-1098',
                'industry' => '小売業',
                'temperature_rating' => 'F',
                'area' => '北海道',
                'status' => '架電禁止',
                'priority' => 1,
                'memo' => '営業電話は全てお断り。メールのみ対応。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社テクノロジーラボ',
                'contact_name' => '森田幸一',
                'email' => 'morita@tech-lab.co.jp',
                'phone' => '03-8765-4321',
                'industry' => 'IT',
                'temperature_rating' => 'A',
                'area' => '関東',
                'status' => '取引中',
                'priority' => 5,
                'memo' => 'メインサービス契約中。アップセル可能性大。',
            ],
            [
                'user_id' => 3,
                'company_name' => '関西製薬',
                'contact_name' => '平野真由美',
                'email' => 'hirano@kansai-pharma.jp',
                'phone' => '06-2109-8765',
                'industry' => '医療・福祉',
                'temperature_rating' => 'B',
                'area' => '関西',
                'status' => '見込みあり',
                'priority' => 4,
                'memo' => '研究データ管理システムに興味あり。',
            ],
            [
                'user_id' => 3,
                'company_name' => '沖縄リゾートホテル',
                'contact_name' => '宮城健太郎',
                'email' => 'miyagi@okinawa-resort.jp',
                'phone' => '098-7654-3210',
                'industry' => '飲食・宿泊',
                'temperature_rating' => 'C',
                'area' => 'その他',
                'status' => '会話のみ',
                'priority' => 3,
                'memo' => '予約管理システムの改善を検討中。',
            ],
            [
                'user_id' => 3,
                'company_name' => '東京インベストメント',
                'contact_name' => '渡辺次郎',
                'email' => 'watanabe@tokyo-investment.jp',
                'phone' => '03-3456-7890',
                'industry' => '金融業',
                'temperature_rating' => 'D',
                'area' => '関東',
                'status' => '過去取引あり',
                'priority' => 2,
                'memo' => '過去に小規模な取引あり。再アプローチ中。',
            ],
            [
                'user_id' => 3,
                'company_name' => '中部ロジスティクス',
                'contact_name' => '近藤美穂',
                'email' => 'kondo@chubu-logistics.co.jp',
                'phone' => '052-9876-5432',
                'industry' => '運輸・物流',
                'temperature_rating' => 'B',
                'area' => '中部',
                'status' => '見込みあり',
                'priority' => 4,
                'memo' => '配送最適化システムの導入を前向きに検討。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社グリーンビルド',
                'contact_name' => '青木健司',
                'email' => 'aoki@green-build.jp',
                'phone' => '045-1234-5678',
                'industry' => '建設・不動産',
                'temperature_rating' => 'A',
                'area' => '関東',
                'status' => '会話のみ',
                'priority' => 5,
                'memo' => 'BIMシステムの導入に興味。予算確保済み。',
            ],
            [
                'user_id' => 3,
                'company_name' => '九州電力サービス',
                'contact_name' => '原田洋子',
                'email' => 'harada@kyushu-power.com',
                'phone' => '092-5432-1098',
                'industry' => 'その他',
                'temperature_rating' => 'E',
                'area' => '九州',
                'status' => '架電禁止',
                'priority' => 1,
                'memo' => '本社経由でないと対応不可。直接架電禁止。',
            ],
            [
                'user_id' => 3,
                'company_name' => 'ウェストファーマ',
                'contact_name' => '小野寺医師',
                'email' => 'onodera@west-pharma.jp',
                'phone' => '082-8765-4321',
                'industry' => '医療・福祉',
                'temperature_rating' => 'C',
                'area' => '中国',
                'status' => '競合サービス利用中',
                'priority' => 3,
                'memo' => '競合のシステムで満足しているが、価格次第では検討可能。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社イーストコマース',
                'contact_name' => '坂本龍馬',
                'email' => 'sakamoto@east-commerce.co.jp',
                'phone' => '03-2109-8765',
                'industry' => '小売業',
                'temperature_rating' => 'B',
                'area' => '関東',
                'status' => '取引中',
                'priority' => 4,
                'memo' => 'ECプラットフォーム利用中。追加機能の提案可能。',
            ],
            [
                'user_id' => 3,
                'company_name' => '北日本教育センター',
                'contact_name' => '千葉先生',
                'email' => 'chiba@kita-nihon-edu.ac.jp',
                'phone' => '022-5678-9012',
                'industry' => '教育',
                'temperature_rating' => 'D',
                'area' => '東北',
                'status' => '受けブロ',
                'priority' => 2,
                'memo' => '予算の関係で導入は困難。',
            ],
            [
                'user_id' => 3,
                'company_name' => 'サウスコンサルティング',
                'contact_name' => '南税理士',
                'email' => 'minami@south-consulting.jp',
                'phone' => '06-3456-7890',
                'industry' => '士業・コンサル',
                'temperature_rating' => 'B',
                'area' => '関西',
                'status' => '見込みあり',
                'priority' => 4,
                'memo' => '顧客管理システムの導入に前向き。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社デジタルワークス',
                'contact_name' => '北村大輔',
                'email' => 'kitamura@digital-works.jp',
                'phone' => '03-9876-5432',
                'industry' => 'IT',
                'temperature_rating' => 'C',
                'area' => '関東',
                'status' => '過去取引あり',
                'priority' => 3,
                'memo' => '過去にトライアル利用。再度提案の機会あり。',
            ],
            [
                'user_id' => 3,
                'company_name' => 'ノースレストラン',
                'contact_name' => '東オーナー',
                'email' => 'azuma@north-restaurant.com',
                'phone' => '011-1234-5678',
                'industry' => '飲食・宿泊',
                'temperature_rating' => 'F',
                'area' => '北海道',
                'status' => '架電禁止',
                'priority' => 1,
                'memo' => 'チェーン本部経由でのみ対応。店舗への直接連絡禁止。',
            ],
            [
                'user_id' => 3,
                'company_name' => '中央金融サービス',
                'contact_name' => '西田部長',
                'email' => 'nishida@central-finance.jp',
                'phone' => '052-5432-1098',
                'industry' => '金融業',
                'temperature_rating' => 'A',
                'area' => '中部',
                'status' => '見込みあり',
                'priority' => 5,
                'memo' => 'システム全面刷新を計画中。大型案件の可能性。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社サンライズ物流',
                'contact_name' => '日高課長',
                'email' => 'hidaka@sunrise-logistics.jp',
                'phone' => '087-8765-4321',
                'industry' => '運輸・物流',
                'temperature_rating' => 'B',
                'area' => '四国',
                'status' => '会話のみ',
                'priority' => 3,
                'memo' => 'トラッキングシステムの改善に興味あり。',
            ],
            [
                'user_id' => 3,
                'company_name' => 'ウェスタン開発',
                'contact_name' => '山口社長',
                'email' => 'yamaguchi@western-dev.co.jp',
                'phone' => '082-2109-8765',
                'industry' => '建設・不動産',
                'temperature_rating' => 'C',
                'area' => '中国',
                'status' => '競合サービス利用中',
                'priority' => 2,
                'memo' => '既存システムから切り替えは当面考えていない。',
            ],
            [
                'user_id' => 3,
                'company_name' => '株式会社モダンリテール',
                'contact_name' => '福田店長',
                'email' => 'fukuda@modern-retail.jp',
                'phone' => '092-5678-9012',
                'industry' => '小売業',
                'temperature_rating' => 'A',
                'area' => '九州',
                'status' => '取引中',
                'priority' => 5,
                'memo' => 'POSシステム導入済み。在庫管理システムも追加検討中。',
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }

        $this->command->info('user_id = 3に対して30件の顧客データを作成しました。');
    }
}